# Site settings
title: That C# guy
email: antonio.feregrino@hotmail.es
description: > # this means to ignore newlines until "baseurl:"
  Escribo sobre ciencias computacionales, principalmente enfocado a la programación de aplicaciones, pero con énfasis en C#, mi lenguaje favorito. A veces me da por escribir sobre tecnología también. 
description-en: > # this means to ignore newlines until "baseurl:"
  Blog about computer science, mainly focused on application programming, emphasizing C# development, my favourite language. Sometimes I write about technology in general too. 
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://thatcsharpguy.com" # the base hostname & protocol for your site
url: "http://127.0.0.1:4000"
images_url: "http://127.0.0.1:4000/postimages"
twitter_username: io_exception
github_username: fferegrino

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/