# Site settings
title: That C# guy
email: antonio.feregrino@hotmail.es
description: > # this means to ignore newlines until "baseurl:"
  Blog sobre ciencias computacionales, principalmente enfocado a la programación de aplicaciones, pero con énfasis en C#, mi lenguaje favorito. A veces me da por escribir sobre tecnología también. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thatcsharpguy.com" # the base hostname & protocol for your site
twitter_username: io_exception
github_username: fferegrino

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:lang/:title/
