# Site settings
title: That C# guy
email: antonio.feregrino@hotmail.es
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thatcsharpguy.com" # the base hostname & protocol for your site
twitter_username: io_exception
github_username: fferegrino

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/
