# Site settings
title: That C# guy
email: feregrino@thatcsharpguy.com
description: > # this means to ignore newlines until "baseurl:"
  Escribo sobre ciencias computacionales, principalmente enfocado a la programación de aplicaciones, pero con énfasis en C#, mi lenguaje favorito. A veces me da por escribir sobre tecnología también. 
description-en: > # this means to ignore newlines until "baseurl:"
  Blog about computer science, mainly focused on application programming, emphasizing C# development, my favourite language. Sometimes I write about technology in general too. 
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://thatcsharpguy.com" # the base hostname & protocol for your site
url: "http://thatcsharpguy.com"
images_url: "http://thatcsharpguy.com/postimages"
assets_url: "http://thatcsharpguy.com/assets"
twitter_username: io_exception
github_username: fferegrino

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /post/:title/


excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed



defaults:
  -
    scope:
      path: "en"
    values:
      lang: "en" # overrides previous default layout
  -
    scope:
      path: "es"
    values:
      lang: "es"
  -
    scope:
      path: ""
      type: "post"
    values:
      comments: true
      
      
t:
    en:
        menus:
            home_m:
                title: "Home"
                url: "/"
            about_m:
                title: "About"
                url: "/about"
            tags_m:
                title: "Tags"
                url: "/tag"
            signup_m:
                title: "Sign up"
                url: "/signup"
        # Texto general
        home: "Inicio"
        findMeOn: "Find me on"
        postContact: Questions, comments? escríbeme sobre esto a <a href='mailto:{{ site.email }}?subject={{ page.title }}'>{{ site.email }}</a>, a <a href='https://twitter.com/intent/tweet?text=@{{ site.twitter_username }} sobre {{ page.title }}'>@{{ site.twitter_username }}</a> o <a href='javascript:loadComments();'>deja un comentario</a>. <strong>¿Quieres estar al tanto de mis posts? <a href='/registro'>regístrate aquí</a>.</strong>
    es:
        menus:
            home_m:
                title: "Inicio"
                url: "/"
            about_m:
                title: "Acerca de"
                url: "/acerca-de"
            tags_m:
                title: "Tags"
                url: "/tag"
            signup_m:
                title: "Regístrate"
                url: "/unete"
        # Texto general:
        home: "Inicio"
        findMeOn: "Encuéntrame en"
        postContact: ¿Dudas o comentarios? escríbeme sobre esto a <a href='mailto:{{ site.email }}?subject={{ page.title }}'>{{ site.email }}</a>, a <a href='https://twitter.com/intent/tweet?text=@{{ site.twitter_username }} sobre {{ page.title }}'>@{{ site.twitter_username }}</a> o <a href='javascript:loadComments();'>deja un comentario</a>. <strong>¿Quieres estar al tanto de mis posts? <a href='/registro'>regístrate aquí</a>.</strong>