# Site settings
title: That C# guy
email: feregrino@thatcsharpguy.com
description: > # this means to ignore newlines until "baseurl:"
  Escribo sobre ciencias computacionales, principalmente enfocado a la programación de aplicaciones, pero con énfasis en C#, mi lenguaje favorito. A veces me da por escribir sobre tecnología también. 
description-en: > # this means to ignore newlines until "baseurl:"
  Blog about computer science, mainly focused on application programming, emphasizing C# development, my favourite language. Sometimes I write about technology in general too. 
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://thatcsharpguy.com" # the base hostname & protocol for your site
url: "http://thatcsharpguy.com"
images_url: "http://thatcsharpguy.com/postimages"
twitter_username: io_exception
github_username: fferegrino

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed



defaults:
  -
    scope:
      path: "en"
      type: "posts" # previously `page` in Jekyll 2.2.
    values:
      lang: "en" # overrides previous default layout
  -
    scope:
      path: "en"
      type: "drafts" # previously `page` in Jekyll 2.2.
    values:
      lang: "en" # overrides previous default layout
  -
    scope:
      path: "es"
      type: "posts" # previously `page` in Jekyll 2.2.
    values:
      lang: "es" # overrides previous default layout
  -
    scope:
      path: "es"
      type: "drafts" # previously `page` in Jekyll 2.2.
    values:
      lang: "es" # overrides previous default layout
  -
    scope:
      path: ""
      type: "posts" # previously `page` in Jekyll 2.2.
    values:
      author: Antonio Feregrino Bolaños


